name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: yarn install
      run: yarn install
   
    # - name: yarn workspace server delete stuff
    #   run: yarn workspace server delete stuff
    - name: run script
      run: packages/server/routes/app.ts
      
    
