name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: yarn install
      run: yarn install
      shell: cmd
    - name: yarn workspace server delete stuff
      run: yarn workspace server delete stuff
      shell: cmd
